Add key size validation for AddEncryptionKey
openiddict/openiddict-core pull request #1152
Opened 2020-10-28 05:30 UTC by NoahStahl

To address #1151 

I believe for the symmetric key case we just need to check the KeySize property which is expected to be 256 based on that as the supported algorithm. I added an exception message and associated tests following the existing pattern.

I'm not sure what should be expected with the asymmetric case as to the key size, so no changes made there.

2020-10-28 14:42 UTC, kevinchalet requested changes

2020-10-28 14:42 UTC, kevinchalet commented on src/OpenIddict.Abstractions/Resources/OpenIddictResources.resx
> +    <value>Provided symmetric key was incorrect size. Must be 256 bits derived from exactly 32 bytes or string of length 32.</value>
Can you please make it parametrized? Also, I'd remove the `derived from exactly 32 bytes or string of length 32` part, which is a bit confusing.

2020-10-28 14:42 UTC, kevinchalet commented on src/OpenIddict.Abstractions/Resources/OpenIddictResources.resx
> +  </data>
Please add `<comment>{Locked}</comment>` to ensure it's not localized.

2020-10-28 14:42 UTC, kevinchalet commented on src/OpenIddict.Server/OpenIddictServerBuilder.cs
> +                    throw new ArgumentOutOfRangeException(nameof(key), SR.GetResourceString(SR.ID0283));
Let's use `InvalidOperationException` to match the other exceptions thrown from this method.

2020-10-28 14:42 UTC, kevinchalet commented on test/OpenIddict.Server.Tests/OpenIddictServerBuilderTests.cs
> +            Assert.Equal("key", exception.ParamName);
We'll also need to check the actual error message.

2020-10-28 14:42 UTC, kevinchalet commented on test/OpenIddict.Server.Tests/OpenIddictServerBuilderTests.cs
> +            Assert.Equal("key", exception.ParamName);
Here too.

2020-10-28 14:42 UTC, kevinchalet commented
Thanks for your PR!

2020-10-29 03:04 UTC, NoahStahl commented
@kevinchalet Thanks for the feedback. I've added the suggested changes.

2020-10-31 15:33 UTC, kevinchalet approved these changes

2020-10-31 15:33 UTC, kevinchalet commented on src/OpenIddict.Server/OpenIddictServerBuilder.cs
> +        /// <param name="key">The security key. If a SymmetricSecurityKey, create using a 32-character
Technically, this comment is not 100% exact, as the check doesn't only applies to `SymmetricSecurityKey` instances (e.g you could have a `JsonWebKey` instance representing a symmetric key). Let's revert this change, please.

2020-10-31 15:33 UTC, kevinchalet commented on test/OpenIddict.Server.Tests/OpenIddictServerBuilderTests.cs
> +            Assert.Equal("Provided symmetric key was incorrect size. Expected 256 bits, received 128.", exception.Message);
Please use `SR.FormatID0283(256, 128)` here.

2020-10-31 15:33 UTC, kevinchalet commented on test/OpenIddict.Server.Tests/OpenIddictServerBuilderTests.cs
> +            Assert.Equal("Provided symmetric key was incorrect size. Expected 256 bits, received 384.", exception.Message);
Same here.

2020-11-02 23:24 UTC, NoahStahl commented
Thanks for additional comments Kevin, changes made. Sorry for additional commit, got confused there for a moment.

2020-11-03 00:16 UTC, merged

2020-11-03 00:16 UTC, kevinchalet commented
Merged, thanks for your contribution!